pkg/managed/clusterroles.go
This pull request fixes a permission error when adding/removing a domain namespace for a weblogic-kubernetes-operator. 
Change was to add the patch permission for clusterrolebinding and rolebinding to the verrazzano-system clusterrole.
Jira: https://jira.oraclecorp.com/jira/browse/VZ-953
=> Update verrazzano-system clusterrole to fix weblogic-operator permission error

pkg/managed/istio.go, pkg/managed/istio_test.go, pkg/managed/testutils.go, pkg/util/utils.go
Part of a larger effort to improve unit test coverage.  
Add missing unit tests for istio.go in verrazzano-operator.
- Refactor util.ManagedClusterConnection to use interface (kubernetes.Interface)
- Refactor istio.go methods to pass in cluster connections (mock friendly)
- Add unit tests for DestinationRule and AuthorizationPolicy creation
- Add test utility for creating mock cluster connections (importing fake packages for client set interfaces)
=> Add unit tests for verrazzano-operator istio.go (DestinationRule & AuthorizationPolicy)

cmd/verrazzano-operator/main.go, pkg/constants/constants.go, pkg/controller/controller.go, pkg/controller/model_binding_pair.go, pkg/controller/model_binding_pair_test.go, pkg/managed/serviceaccount.go, pkg/types/types.go
If optional imagePullSecrets on set on the verrazzano-operator service account (in namespace verrazzano-system), copy them into service accounts created by the verrazzano-operator.
This is required because the docker images associated with the deployments the created by the verrazzano-operator may be protected by the same imagePullSecrets.
=> Propagate imagePullSecrets from operator service account

pkg/controller/secrets_test.go
Fix test function capitalization.  Only exported test functions are executed.
https://build.verrazzano.io/job/verrazzano-operator/job/kminder%252FVZ-1306-3/ passing
=> VZ-1306: Fix test func name

pkg/controller/controller.go, pkg/managed/clusterroles.go, pkg/managed/clusterroles_test.go, pkg/testutil/fakes.go, pkg/testutil/fakes_test.go, pkg/testutil/testdata.go
Add unit tests for clusterroles.go.
Changes previously approved in PR https://github.com/verrazzano/verrazzano-operator/pull/145.
Needed to move the changes to this new branch to get around a messed up code coverage check that was blocking the other branch.
Acceptance tests with operator changes in this PR:
https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/tbeerbower%2Ftest-VZ-1337-2/1/pipeline
=> Unit tests for verrazzano-operator clusterroles.go

Makefile, THIRD_PARTY_LICENSES.txt, go.mod, go.sum, pkg/api/instance/instance.go, pkg/api/instance/instance_test.go, pkg/util/apiserver/cors.go, pkg/util/apiserver/cors_test.go, pkg/util/apiserver/handlers.go, pkg/util/env.go
Make API CORS `Access-Control-Allow-Origin` header specific to console instead of "*", with ability to override (needed when UI is run locally for testing purposes, for example)
Also refactored instance_test.go to cover more cases
=> Make API CORS header specific to console

pkg/api/microservices/microservices_test.go
Looks like the order of `myMicroservices` isn't guaranteed.
=> Intermittent failure in TestReturnAllMicroservices

cmd/verrazzano-operator/main.go
Adds ability to start _just_ the API server in verrazzano-operator without starting controller. This will help in running UI tests against a version of verrazzano-operator that will not do any work in Kubernetes in response to deployments
=> VZ1287 add startController flag

THIRD_PARTY_LICENSES.txt, go.mod, go.sum, pkg/api/secrets/secrets_test.go, pkg/controller/controller.go, pkg/controller/model_binding_pair.go, pkg/controller/model_binding_pair_test.go, pkg/controller/testdata/generic-binding.yaml, pkg/controller/testdata/generic-model.yaml, pkg/genericcomp/genericcomp.go, pkg/genericcomp/genericcomp_test.go, pkg/helidonapp/helidonapp_test.go, pkg/managed/configmaps.go, pkg/managed/crs.go, pkg/managed/deployment.go, pkg/managed/deployment_test.go, pkg/managed/secrets.go, pkg/managed/serviceaccount_test.go, pkg/managed/services.go, pkg/managed/services_test.go, pkg/testutil/testdata/test_binding.yaml, pkg/testutil/testdata/test_managed_cluster_1.yaml, pkg/testutil/testdata/test_model.yaml, pkg/types/types.go
This pull request contains the initial implementation of generic components in the verrazzano-operator.  In addition, unit tests are included for all new code.  A generic component will result in a k8s deployment and optionally a k8s service being created.  The initial implementation includes support for rest and ingress connections.
=> Initial support for generic components

pkg/wlsdom/wlsdomain.go, pkg/wlsdom/wlsdomain_test.go
Increase the timeout of the *-introspect-domain-job from 5 minutes to 10 minutes.
=> VZ-1441: increase model default for domaincrvalues.configuration.introspectorjobactivedeadlineseconds

.gitignore, Makefile, test/create-deployment.sh
Do some minor cleanup:
1. Makefile add `go mod tidy` to prevent go.mod and go.sum from being modified and checked out.  
2. Add build/deploy to .gitignore
3. Remove cert logic no longer needed
=> Minor cleanup of makefile and gitignore

Makefile, cmd/verrazzano-operator/main.go, cmd/verrazzano-operator/main_test.go, pkg/fluentd/fluentd_test.go, pkg/local/vmis.go, pkg/local/vmis_test.go, pkg/util/env.go, pkg/util/utils.go, pkg/util/utils_test.go, run-vo.sh
Re-interpret the notion of install profiles to be a set of fine-grained install-time configuration options, instead of an explicit single global switch.  This change introduces those settings, and how they are used for "dev" vs. "prod" install profiles.
The notion of profiles will then be implemented in the installer through collections of values for a subset of these settings; e.g., the "dev" profile will have a set of values that will correspond to a shared VMI and a single-node ES cluster, without an explicit need for a "profile" switch in the code.
ES_MASTER_NODE_REQUEST_MEMORY
ES_MASTER_NODE_REPLICAS
Setting | Operator Behavior
-- | -- 
USE_SYSTEM_VMI | When set to true, indicates that we should use the System VMI for all application data by default
ES_DATA_NODE_REPLICAS | The number …
=> VZ-1740.  Productize dev/prod profiles

pkg/local/configmaps.go, pkg/util/env_test.go, pkg/util/utils.go, pkg/util/utils_test.go
This change makes the default dashboards which are normally installed to each Application VMO to single VMI, for dev profile. I can see the change https://github.com/verrazzano/verrazzano-operator/pull/205, renaming the method IsDevProfile(), based on which change goes first, a change will be required in the other one.
Acceptance test with the change : https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/pabhat%2Facc_test_develop/4/pipeline
=> VZ-1653 : Configure application dashboard for dev profile

pkg/managed/secrets.go, pkg/managed/secrets_test.go, pkg/testutil/testdata.go, pkg/testutil/testdata/test_managed_cluster_1.yaml
This addresses Verrazzano [issue 339](https://github.com/verrazzano/verrazzano/issues/339). We now copy any arbitrary Weblogic domain secrets when we're propagating secrets in the operator.
I'm not 100% confident that I did this correctly. Specifically I'm unsure if the namespacing is correct.
=> VZ-1596: Copy arbitrary WLS secrets when creating secrets

pkg/wlsdom/wlsdomain.go, pkg/wlsdom/wlsdomain_test.go
This is the second PR to address https://github.com/verrazzano/verrazzano/issues/339. We were only copying DB secrets and this fix also copies domain secrets specified in the model.
I added unit tests but we should probably add integration tests for this at some point. I'll create a ticket to track that.
I also tested manually and confirmed that secrets are copied correctly to the target namespace.
=> VZ-1596: Copy WLS domain secrets from model

pkg/fluentd/fluentd_test.go, pkg/util/utils.go, pkg/wlsdom/fluentd.go, pkg/wlsdom/wlsdomain_test.go
If shared VMI is configured, the WLS fluentd sidecar should use that Elasticsearch host instead of looking for the binding ES host
=> WLS fluentd sidecar should use right VMI

pkg/monitoring/constants.go
The cert-manager and keycloak pods use a dot-notated form for names in their labels, which is causing filebeat to create an object for such entries instead of a text field; Filebeat/ES support a notion of "dedot"-ing such fields to make flat names.
This change enables the dedot capability which seems to be allowing cert-manager and keycloak pod logs to be captured successfully, although we're still getting warnings/debug messages about collisions on the kubernetes.labels.app field.
=> VZ-1667.  Fix filebeat processing of cert-manager/keycloak k8s labels fields

pkg/api/instance/instance.go, pkg/api/instance/instance_test.go
In case of shared/system vmi, the application telemetry links on console binding details page need to be same as system telemetry links on home page. This change to add a new field `IsUsingSharedVMI` to the instance api response to send the information about shared vmi being used or not to console. Corresponding UI changes in https://github.com/verrazzano/console/pull/40
=> Changes to instance api to include information for shared vmi

pkg/wlsdom/wlsdomain.go, pkg/wlsdom/wlsdomain_test.go
During testing of the todo app, we found a bug in the Verrazzano Operator.
In this line of code: 
https://github.com/verrazzano/verrazzano-operator/blob/89f29d969c5bab15def74da2d2834ae93c9abef7/pkg/wlsdom/wlsdomain.go#L118
`Secrets: append(domainCRValues.Configuration.Secrets, dbSecrets...),`
The `Secrets` slice needs to be deduplicated after this `append()` is done.  
If the WebLogic Kubernetes Operator encounters a list of secrets in a domain CR under `spec.configuration.secrets` with duplicate entries, it prints a validation error and refuses to start the domain.
My fix introduces code to remove duplicates from the list after the append, and unit tests for that new code. 
I have tested this manually, and am working on getting an acceptance test run now.
=> Fix bug in Verrazzano operator which caused duplicate secrets to be sent to WKO

Makefile, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/managed/configmaps.go, pkg/managed/configmaps_test.go, pkg/managed/daemonsets.go, pkg/managed/daemonsets_test.go, pkg/monitoring/configmaps.go, pkg/monitoring/configmaps_test.go, pkg/monitoring/constants.go, pkg/monitoring/daemonsets.go, pkg/monitoring/daemonsets_test.go
Changes to support logging to Elasticsearach in a Kubernetes cluster with a Containerd container runtime.
Previously, Verrazzano system components only logged to Elasticsearch in a Docker environment. The paths to which the logs are written to by the Kubernetes log driver are different across container runtimes.
=> Fix Verrazzano system component logging when using Containerd container runtime

pkg/managed/utils.go, pkg/util/env.go
follow the same idea as verrazzano/verrazzano#673.
=> use nodeport instead of ingress address to access rancher at runtime.

pkg/monitoring/constants.go
Regardless the k8s runtime (containerd or docker), the logs directory is always mounted as /var/lib/docker/containers for filebeats pods.
=> fix filebeat in Kind

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/managed/configmaps.go, pkg/managed/configmaps_test.go, pkg/managed/daemonsets.go, pkg/managed/daemonsets_test.go, pkg/managed/secrets.go, pkg/monitoring/configmaps.go, pkg/monitoring/configmaps_test.go, pkg/monitoring/constants.go, pkg/monitoring/daemonsets.go, pkg/monitoring/daemonsets_test.go, pkg/monitoring/deployment.go, pkg/monitoring/secrets.go, pkg/monitoring/secrets_test.go, pkg/monitoring/utils.go, pkg/monitoring/utils_test.go
VO reads in multicluster information like cluster name and ES details from verrazzano cluster registration secrets to configure filebeat and journalbeat to send logs to the admin ES.
For standalone verrazzano where there is no cluster registration secrets, the beats are configured to log to the local ES.
=> beats multicluster support

pkg/constants/constants.go, pkg/util/utils.go
Though the days of the resources in this namespace are apparently numbered, for the time being the logging namespace is labeled with the istio injection annotation to facilitate communication with other VZ resources.
=> JIRA:VZ-2518 support istio injection for logging namespace

pkg/monitoring/secrets.go, pkg/monitoring/secrets_test.go
These fields are no longer needed due to keycloak config changes.
This PR depends on changes in https://github.com/verrazzano/verrazzano/pull/1099, and shouldn't be merged until that PR is merged.
=> VZ-2490: remove salt and hash fields from secret

THIRD_PARTY_LICENSES.txt, go.mod, go.sum
VMO has been updated to pickup k8s 0.19.2 and controller-runtime 0.6.2, so the VO had to be updated to pickup this new VMO (release as version v0.0.26)
VZ tests confirming these versions work:  https://build.verrazzano.io/job/verrazzano/job/jmaron%252FVZ-3948-testing/8/
Triggered tests (had to be re-run due to spurious issues in OCI DNS and one other suite): https://build.verrazzano.io/job/verrazzano-push-triggered-acceptance-tests/job/jmaron%252FVZ-3948-testing/5/
=> JIRA:VZ-3948 pickup latest VMO in go.mod

THIRD_PARTY_LICENSES.txt, go.mod, go.sum
Update gogo/protobuf dependency version to v1.3.2. 
Task: VZ-3993
=> Jira: VZ-3993 Update gogo/protobuf dependency version to v1.3.2
