- cmd/verrazzano-operator/main.go
- pkg/controller/controller.go
- pkg/controller/model_binding_pair.go
- pkg/controller/model_binding_pair_test.go
- pkg/helidonapp/fluentd.go
- pkg/helidonapp/helidonapp.go
- pkg/helidonapp/helidonapp_test.go
- pkg/types/types.go
- pkg/wlsdom/wlsdomain_test.go
https://jira.oraclecorp.com/jira/browse/VZ-1187
> remove sslVerify

- pkg/cohoperator/cohoperator.go
- pkg/helidonapp/helidonapp.go
- pkg/local/vmis.go
- pkg/util/env.go
- pkg/wlsopr/wlsopr.go
https://jira.oraclecorp.com/jira/browse/VZ-830
related PR:  https://github.com/verrazzano/verrazzano/pull/277
- add memory requests for verrazzano components
- make the VMI memory requests configurable
> add memory requests ENV

- pkg/cohoperator/cohoperator_test.go
Add unit tests for cohoperator.go
> Add unit tests for cohoperator.go

- pkg/cohcluster/cohcluster_test.go
- pkg/cohoperator/cohoperator_test.go
> Unit tests for  cohcluster.go

- pkg/controller/controller.go
- pkg/managed/istio.go
- pkg/managed/istio_test.go
- pkg/managed/testutils.go
- pkg/managed/testutils_test.go
Additional unit tests for istio.go in verrazzano-operator. 
Code coverage for istio.go up to 92%.
Acceptance tests with these verrazzano-operator changes...
https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/tbeerbower%2FVZ-1288/1/pipeline
> Complete unit tests for verrazzano-operator istio.go

- go.sum
- pkg/util/utils_test.go
> add unit test for utils.go

- Jenkinsfile
- Makefile
- go.mod
- go.sum
- pkg/api/applications/applications.go
- pkg/api/jobs/jobs.go
- pkg/cohcluster/cohcluster.go
- pkg/cohcluster/cohcluster_test.go
- pkg/cohoperator/cohoperator_test.go
- pkg/controller/controller.go
- pkg/controller/model_binding_pair.go
- pkg/helidonapp/helidonapp.go
- pkg/local/configmaps.go
- pkg/managed/clusterrolebinding.go
- pkg/managed/clusterroles.go
- pkg/managed/configmaps.go
- pkg/managed/crs.go
- pkg/managed/daemonsets.go
- pkg/managed/istio_test.go
- pkg/managed/istioconfigmap.go
- pkg/managed/istioconfigmap_test.go
- pkg/managed/services.go
- pkg/managed/utils.go
- pkg/monitoring/secrets.go
- pkg/types/types.go
- pkg/util/apiserver/oauth.go
- pkg/util/utils_test.go
- test/integ/util/utils.go
This pull request contains first pass changes for Go Report Card. Addresses all go-fmt, go vet, and ifeffassign issues.
> Initial changes for Go Report Card changes

- pkg/controller/controller.go
- pkg/managed/namespace.go
- pkg/managed/namespace_test.go
- pkg/managed/testutils.go
- pkg/managed/testutils_test.go
Add unit tests for namespace.go in verrazzano-operator.
> Unit tests for verrazzano-operator namespace.go

- pkg/monitoring/clusterroles_test.go
Add unit tests for pkg/monitoring/clusterroles.go
> Add unit tests for pkg/monitoring/clusterroles.go

- pkg/monitoring/clusterrolebinding_test.go
- pkg/monitoring/clusterroles_test.go
Add unit tests for pkg/monitoring/clusterrolebinding
> Add unit tests for pkg/monitoring/clusterrolebinding

- go.sum
- pkg/controller/controller.go
- pkg/managed/services.go
- pkg/managed/services_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
Pull request for adding unit tests for pkg/managed/service.go
>  Add unit tests for pkg/managed/service.go

- pkg/controller/controller.go
- pkg/managed/configmaps.go
- pkg/managed/configmaps_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
Adding unit tests for configmaps.go.
> Unit tests for verrazzano-operator configmaps.go

- pkg/monitoring/doc.go
- pkg/monitoring/utils.go
- pkg/monitoring/utils_test.go
add unit tests for monitoring/utils.go
> add unit tests for monitoring/utils.go

- Makefile
- pkg/api/applications/applications.go
- pkg/api/applications/applications_test.go
- pkg/api/clusters/clusters_test.go
- pkg/testutil/fakes.go
- pkg/testutil/testdata.go
- pkg/testutilcontroller/controllertestdata.go
Also,
- some error handling changes to applications.go
- moved a function from clusters_test.go into the testutil/fakes.go for sharing
>  Add unit tests for pkg/api/applications

- dashboards/system/system_dashboard.json
- pkg/local/configmaps_test.go
fixed/updated CPU panels of system dashboard
> fix cpu panels

- pkg/controller/controller.go
- pkg/managed/clusterrolebinding.go
- pkg/managed/clusterrolebinding_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
Add unit tests for clusterrolebinding.go
> Unit tests for verrazzano-operator clusterrolebinding.go

- pkg/local/configmaps_test.go
- pkg/local/secrets_test.go
- pkg/testutil/fakes.go
unit-test 
* pkg/local/configmaps 
* pkg/local/secrets
> unit-test pkg/local/configmaps and secrets

- pkg/controller/model_binding_pair_test.go
- pkg/controller/testdata/coherence-binding.yaml
- pkg/controller/testdata/coherence-model.yaml
- pkg/controller/testdata/oracle-ds-model-config.yaml
- pkg/controller/testdata/sockshop-binding.yaml
- pkg/controller/testdata/sockshop-model-2.yaml
- pkg/controller/testdata/sockshop-model-no-cluster.yaml
- pkg/controller/testdata/sockshop-model.yaml
Added new unit tests for controller/model_binding_pair.go.
With new tests, this file is ~ 90% COVERAGE.
> VZ-1328: Added unit tests for controller/model_binding_pair.go

- pkg/controller/controller.go
- pkg/local/vmis.go
- pkg/local/vmis_test.go
Also updated the logic in CreateUpdateVmi().
acceptance test runs:  https://build.verrazzano.io/job/verrazzano/job/gz%252FtestVmiRefactoring/
> improve VMI unit test

- pkg/api/operators/operators.go
- pkg/api/operators/operators_test.go
Successful build:  https://build.verrazzano.io/job/verrazzano-operator/job/jmaron%252FVZ-1344/3/
> JIRA:VZ-1344 Unit tests for operators api

- pkg/api/applications/applications_test.go
- pkg/api/grids/grids_test.go
- pkg/api/operators/operators_test.go
- pkg/api/testdata/good_binding.yaml
- pkg/api/testdata/good_model.yaml
- pkg/managed/crds_test.go
- pkg/testutil/testdata.go
- pkg/testutil/testdata/test_binding.yaml
- pkg/testutil/testdata/test_coh_crd.yaml
- pkg/testutil/testdata/test_helidon_crd.yaml
- pkg/testutil/testdata/test_managed_cluster_1.yaml
- pkg/testutil/testdata/test_managed_cluster_2.yaml
- pkg/testutil/testdata/test_model.yaml
- pkg/testutil/testdata/test_wls_crd.yaml
- test/integ/util/utils.go
> Unit tests for verrazzano-operator crds.go

- pkg/controller/controller.go
- pkg/managed/daemonsets.go
- pkg/managed/daemonsets_test.go
- pkg/managed/namespace_test.go
- pkg/managed/serviceaccount_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
Add unit tests for daemonsets.go.
> Unit tests for verrazzano-operator daemonsets.go

- pkg/helidonapp/fluentd.go
- pkg/helidonapp/fluentd_test.go
- pkg/helidonapp/helidonapp.go
- pkg/helidonapp/helidonapp_test.go
- pkg/managed/deployment.go
> unit-test pkg/helidonapp

- pkg/controller/controller.go
- pkg/managed/deployment.go
- pkg/managed/deployment_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
- pkg/testutil/testdata/test_managed_cluster_1.yaml
Add unit tests for  deployment.go.
> Write unit tests for verrazzano-operator deployment.go

- pkg/managed/utils.go
- pkg/managed/utils_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/testdata.go
Add tests for utils.go.
Acceptance tests with operator changes:
https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/test-tbeerbower%2FVZ-1388-4/4/pipeline
https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/test-tbeerbower%2FVZ-1388-4/5/pipeline/
> Unit tests for verrazzano-operator utils.go

- THIRD_PARTY_LICENSES.txt
- cmd/verrazzano-operator/main.go
- go.mod
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/testutil/fakes.go
- pkg/testutil/fakes_test.go
- pkg/testutil/mock.go
- pkg/testutil/mock_test.go
- pkg/testutil/testdata.go
This PR includes adding of unit tests for the V8O Operator Controller.
Additionally, it adds simple generic mocking functionality along with corresponding unit tests.
> VZ-1384: Add unit tests for V8O Controller

- Jenkinsfile
> change coverage limits temp

- pkg/controller/controller.go
During startup, the operator will get the filebeat and journalbeat secrets (in the logging NS) using the client-go lister, then create/update them with the password in the verrazzano secret (in verrazzano-system ns).  There was a race condition where the startup code was not waiting for the lister to sync (load the cache), so the lister get call returned "not found" when, in fact, the secret did exist (but it wasn't yet in the cache). As a result, the subsequent create of the beat secret failed.  This caused the beat pods to fail because the password was missing.
The fix is to wait for the cache to be synced during startup.
> Fix filebeats crash due to missing secret password

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/monitoring/deployment_test.go
- pkg/monitoring/secrets.go
- pkg/monitoring/secrets_test.go
The first part of combining cluster registration secret and cluster elasticsearch secret.
> combine secrets verrazzano-cluster-elasticsearc and verrazzano-cluster-registration

- Dockerfile
Addresses VZ-2418
This pull request removes yum installs that are not needed in the Dockerfile.
> Remove yum installs not needed from Dockerfile

- .verrazzano-development-version
Updating development version from 0.15.0 to 0.16.0
> Updating development version from 0.15.0 to 0.16.0

- .verrazzano-development-version
Updating development version from 0.16.0 to 0.17.0
> Updating development version from 0.16.0 to 0.17.0

- .verrazzano-development-version
Updating development version from 0.17.0 to 0.18.0
> Updating development version from 0.17.0 to 0.18.0

- .verrazzano-development-version
Updating development version from 0.18.0 to 1.1.0
> Updating development version from 0.18.0 to 1.1.0

- .verrazzano-development-version
Updating development version from 1.1.0 to 1.0.1
> Updating development version from 1.1.0 to 1.0.1

- .verrazzano-development-version
Updating development version from 1.0.1 to 1.1.0
> Updating development version from 1.0.1 to 1.1.0

- dashboards/coherence/alerts-dashboard.json
- dashboards/coherence/cache-details-dashboard.json
- dashboards/coherence/caches-summary-dashboard.json
- dashboards/coherence/coherence-dashboard-main.json
- dashboards/coherence/elastic-data-summary-dashboard.json
- dashboards/coherence/federation-details-dashboard.json
- dashboards/coherence/federation-summary-dashboard.json
- dashboards/coherence/http-servers-summary-dashboard.json
- dashboards/coherence/kubernetes-summary-dashboard.json
- dashboards/coherence/machines-summary-dashboard.json
- dashboards/coherence/member-details-dashboard.json
- dashboards/coherence/members-summary-dashboard.json
- dashboards/coherence/persistence-summary-dashboard.json
- dashboards/coherence/proxy-server-detail-dashboard.json
- dashboards/coherence/proxy-servers-summary-dashboard.json
- dashboards/coherence/service-details-dashboard.json
- dashboards/coherence/services-summary-dashboard.json
This PR updates the json for the Coherence dashboards, from Coherence Operator v.3.2.2
> Uptake coherence dashboards from v.3.2.2

- Jenkinsfile
Switch from email to slack notifications
> VZ-3934 move to slack notifications

- Dockerfile
Updates openssl in verrazzano-operator image
> Update openssl in verrazzano-operator image

- .verrazzano-development-version
Updating development version from 1.1.0 to 1.2.0
> Updating development version from 1.1.0 to 1.2.0

- Jenkinsfile
- THIRD_PARTY_LICENSES.txt
- go.mod
- go.sum
This PR updates dependencies and also fixes a broken image scan stage in the CI/CD pipeline.
> VZ-4727: Update dependencies, fix image scanning

- cmd/verrazzano-operator/main.go
- pkg/controller/controller.go
- pkg/local/configmaps.go
- pkg/local/secrets.go
- pkg/local/vmis.go
- pkg/managed/namespace.go
- pkg/monitoring/secrets.go
- pkg/util/env.go
- pkg/util/logs/logs.go
- pkg/util/utils.go
First pass at logging cleanup for error messages
> VZ-4758 Verrazzano Operator logging cleanup

- Jenkinsfile
- dashboards/helidon/helidon_dashboard.json
- tools.go
- Fixes Helidon dashboard to work correctly with multicluster
> VZ-5168: Fix Helidon dashboard to work correctly with multicluster
